spring:
  datasource:
    url: jdbc:mysql://144.24.68.69:3306/testdb
    username: yang
    password: Rlagus12!@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      #      ddl-auto: create
      ddl-auto: update
      #  ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        # show_sql: true
        # order_inserts: true
        # generate_statistics: true
        # cache:
        #   use_second_level_cache: true
        #   use_query_cache: true
    logging.level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace

  servlet:
    multipart:
      max-file-size: 20MB #최대 파일 사이즈를 20MB로 지정#

  web:
    resources:
      static-locations: classpath:/static/

server:
  port: 8090
